[package]
name = "itp-utils"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
homepage = "https://integritee.network/"
repository = "https://github.com/integritee-network/worker/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
cid = { version = "0.10.1", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
log = "0.4.28"
multibase = { version = "0.9.1", default-features = false }
multihash = { version = "0.18.0", default-features = false, features = ["alloc", "multihash-impl", "sha2"] }

[features]
default = ["std"]
std = [
    "cid/std",
    "multibase/std",
    "codec/std",
    "hex/std",
]
